// Every table hexframe keeps, in Drizzle's schema language. `drizzle-kit generate` diffs this file
// against the last migration's snapshot and writes the next migration into ../../../migrations/.
// Tables arrive with the domains that own them: IAM's, then Mapping's, then Assistant's.
import { eq, inArray, isNull } from 'drizzle-orm'
import {
  type AnyPgColumn,
  bigint,
  boolean,
  check,
  index,
  integer,
  json,
  jsonb,
  pgTable,
  smallint,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core'

// IAM's, in Better Auth's shape and under its names (../auth/CLAUDE.md): its `user` is IAM's Account,
// its `account` one way an Account signs in. Generated by Better Auth's Drizzle schema generator.

export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').default(false).notNull(),
  image: text('image'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at')
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
})

export const session = pgTable(
  'session',
  {
    id: text('id').primaryKey(),
    expiresAt: timestamp('expires_at').notNull(),
    token: text('token').notNull().unique(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
  },
  (table) => [index('session_userId_idx').on(table.userId)],
)

export const account = pgTable(
  'account',
  {
    id: text('id').primaryKey(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at'),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at'),
    scope: text('scope'),
    password: text('password'),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index('account_userId_idx').on(table.userId)],
)

export const verification = pgTable(
  'verification',
  {
    id: text('id').primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: timestamp('expires_at').notNull(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index('verification_identifier_idx').on(table.identifier)],
)

/** Better Auth's rate limiter: one row per client IP and endpoint, counting its recent calls. */
export const rateLimit = pgTable('rate_limit', {
  id: text('id').primaryKey(),
  key: text('key').notNull().unique(),
  count: integer('count').notNull(),
  lastRequest: bigint('last_request', { mode: 'number' }).notNull(),
})

/**
 * Better Auth's api-key plugin: IAM's Keys, one row each, owned by the user `reference_id` names. `key`
 * holds the secret's hash, never the secret; `start`, its first characters, to tell Keys apart. Its
 * usage and rate-limit columns stay unused (../auth/CLAUDE.md). The plugin's own schema has no key to
 * `user`: this one has, so deleting an Account deletes its Keys rather than leaving them to prove it.
 */
export const apikey = pgTable(
  'apikey',
  {
    id: text('id').primaryKey(),
    configId: text('config_id').default('default').notNull(),
    name: text('name'),
    start: text('start'),
    referenceId: text('reference_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    prefix: text('prefix'),
    key: text('key').notNull(),
    refillInterval: integer('refill_interval'),
    refillAmount: integer('refill_amount'),
    lastRefillAt: timestamp('last_refill_at'),
    enabled: boolean('enabled').default(true),
    rateLimitEnabled: boolean('rate_limit_enabled').default(true),
    rateLimitTimeWindow: integer('rate_limit_time_window').default(86_400_000),
    rateLimitMax: integer('rate_limit_max').default(10),
    requestCount: integer('request_count').default(0),
    remaining: integer('remaining'),
    lastRequest: timestamp('last_request'),
    expiresAt: timestamp('expires_at'),
    createdAt: timestamp('created_at').notNull(),
    updatedAt: timestamp('updated_at').notNull(),
    permissions: text('permissions'),
    metadata: text('metadata'),
  },
  (table) => [
    index('apikey_configId_idx').on(table.configId),
    index('apikey_referenceId_idx').on(table.referenceId),
    uniqueIndex('apikey_key_idx').on(table.key),
  ],
)

/** What a `tile` row's `config` holds: a folder's naming, either part of it left out when not set. */
export interface TileConfigColumn {
  readonly fileName?: string | undefined
  readonly folderPattern?: string | undefined
}

/** What a `tile` row's `frontmatter` holds: the keys an imported file carried, each a scalar. */
export type FrontmatterColumn = Readonly<Record<string, string | number | boolean>>

// Mapping's (./tiles/tiles.ts): every Tile of every System, and the References standing in Context slots.

/**
 * A row is a Tile or, when `target` is set, a Reference to the Tile of that id, standing in a Context
 * slot, whose content columns stay empty. A Root has no parent and no direction: one per Account. Any
 * other row stands under its parent in a direction: 1 to 6 for a Branch, 7 to 12 for a Leaf, its
 * Direction past the six Branch slots, so a Leaf and a Branch may share a Direction, and -1 to -6 for
 * a Context slot. One row at most holds a slot; the checks refuse any other, which would hold a slot
 * no reader sees. Deleting a row deletes everything below it; a Reference to it has no key to it, so it stays,
 * broken. `account_id` has no key to `user`: Mapping ignores IAM (hexframe-v0-mapping DEC-1).
 * `name`, `config` and `frontmatter` keep what an imported file carried, each null when it carried
 * nothing: the name it was imported under, its folder's settings and the frontmatter keys Mapping has no
 * use for, both as JSON objects, the latter in its file's order. Mapping bounds them before writing them and decides what they mean.
 * `version` is the Tile's Version, which a write names to be refused once the Tile changed since.
 * `system_version` is the System's Version, kept on its Root's row, which a client polls.
 */
export const tile = pgTable(
  'tile',
  {
    id: text('id').primaryKey(),
    accountId: text('account_id').notNull(),
    parentId: text('parent_id').references((): AnyPgColumn => tile.id, { onDelete: 'cascade' }),
    direction: smallint('direction'),
    title: text('title').notNull(),
    preview: text('preview').notNull(),
    body: text('body').notNull(),
    target: text('target'),
    name: text('name'),
    config: jsonb('config').$type<TileConfigColumn>(),
    // json, not jsonb, which would sort the keys: Frontmatter keeps the order its file gave.
    frontmatter: json('frontmatter').$type<FrontmatterColumn>(),
    // A Tile's Version: how many events touched it, 1 once created. Mapping decides it; a Reference's
    // row keeps 1, since its own create and delete count on the Tile whose Context slot they change.
    version: integer('version').default(1).notNull(),
    // The System's Version, on its Root's row, the one every change locks: how many events changed
    // the System, 0 before the first. Mapping decides it; every other row keeps 0, unread.
    systemVersion: integer('system_version').default(0).notNull(),
  },
  (table) => [
    index('tile_accountId_idx').on(table.accountId),
    uniqueIndex('tile_root_idx').on(table.accountId).where(isNull(table.parentId)),
    uniqueIndex('tile_slot_idx').on(table.parentId, table.direction),
    check('tile_root_check', eq(isNull(table.parentId), isNull(table.direction))),
    check(
      'tile_direction_check',
      inArray(table.direction, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, -1, -2, -3, -4, -5, -6]),
    ),
  ],
)

// Assistant's (./conversations/conversations.ts): each Account's Conversation, and its Entries.

/**
 * An Account's Conversation, one at most, added with its first Entry. `account_id` has no key to
 * `user`, as `tile`'s has none: Assistant ignores IAM.
 */
export const conversation = pgTable('conversation', {
  id: text('id').primaryKey(),
  accountId: text('account_id').notNull().unique(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
})

/**
 * An Entry of a Conversation, at the instant it dates from: `content` is the Entry as Assistant
 * encodes it, which Assistant decodes and bounds, never the repository. `seq` orders two Entries of
 * the same instant as they were written. Deleting a Conversation deletes its Entries.
 */
export const conversationEntry = pgTable(
  'conversation_entry',
  {
    id: text('id').primaryKey(),
    conversationId: text('conversation_id')
      .notNull()
      .references(() => conversation.id, { onDelete: 'cascade' }),
    at: timestamp('at', { withTimezone: true }).notNull(),
    seq: bigint('seq', { mode: 'number' }).generatedAlwaysAsIdentity(),
    content: jsonb('content').notNull(),
  },
  (table) => [
    index('conversation_entry_at_idx').on(table.conversationId, table.at, table.seq),
    // The Entry last written, which the page polls: one row read from the end of this index.
    index('conversation_entry_seq_idx').on(table.conversationId, table.seq),
  ],
)
