// Every table hexframe keeps, in Drizzle's schema language. `drizzle-kit generate` diffs this file
// against the last migration's snapshot and writes the next migration into ../../../migrations/.
// Tables arrive with the domains that own them: IAM's, then Mapping's.
import { isNull } from 'drizzle-orm'
import {
  type AnyPgColumn,
  bigint,
  boolean,
  index,
  integer,
  pgTable,
  smallint,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core'

// IAM's, in Better Auth's shape and under its names (../auth/CLAUDE.md): its `user` is IAM's Account,
// its `account` one way an Account signs in. Generated by Better Auth's Drizzle schema generator.

export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').default(false).notNull(),
  image: text('image'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at')
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
})

export const session = pgTable(
  'session',
  {
    id: text('id').primaryKey(),
    expiresAt: timestamp('expires_at').notNull(),
    token: text('token').notNull().unique(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
  },
  (table) => [index('session_userId_idx').on(table.userId)],
)

export const account = pgTable(
  'account',
  {
    id: text('id').primaryKey(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at'),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at'),
    scope: text('scope'),
    password: text('password'),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index('account_userId_idx').on(table.userId)],
)

export const verification = pgTable(
  'verification',
  {
    id: text('id').primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: timestamp('expires_at').notNull(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index('verification_identifier_idx').on(table.identifier)],
)

/** Better Auth's rate limiter: one row per client IP and endpoint, counting its recent calls. */
export const rateLimit = pgTable('rate_limit', {
  id: text('id').primaryKey(),
  key: text('key').notNull().unique(),
  count: integer('count').notNull(),
  lastRequest: bigint('last_request', { mode: 'number' }).notNull(),
})

// Mapping's (./tiles/tiles.ts): every Tile of every System, and the References standing in Context slots.

/**
 * A row is a Tile or, when `target` is set, a Reference to the Tile of that id, standing in a Context
 * slot, whose content columns stay empty. A Root has no parent and no direction: one per Account. Any
 * other row stands under its parent in a direction, 1 to 6 for a Child, -1 to -6 for a Context slot,
 * and one row at most holds a slot. Deleting a row deletes everything below it; a Reference to it has
 * no key to it, so it stays, broken.
 */
export const tile = pgTable(
  'tile',
  {
    id: text('id').primaryKey(),
    accountId: text('account_id').notNull(),
    parentId: text('parent_id').references((): AnyPgColumn => tile.id, { onDelete: 'cascade' }),
    direction: smallint('direction'),
    title: text('title').notNull(),
    preview: text('preview').notNull(),
    body: text('body').notNull(),
    target: text('target'),
  },
  (table) => [
    index('tile_accountId_idx').on(table.accountId),
    uniqueIndex('tile_root_idx').on(table.accountId).where(isNull(table.parentId)),
    uniqueIndex('tile_slot_idx').on(table.parentId, table.direction),
  ],
)
