/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './front/routes/__root'
import { Route as IndexRouteImport } from './front/routes/index'
import { Route as DevRouteRouteImport } from './front/routes/dev/route'
import { Route as HelpRouteImport } from './front/routes/help'
import { Route as McpRouteImport } from './front/routes/mcp'
import { Route as accessSignInRouteImport } from './front/routes/(access)/sign-in'
import { Route as accessSignUpRouteImport } from './front/routes/(access)/sign-up'
import { Route as DevErrorsRouteImport } from './front/routes/dev/errors'
import { Route as DevHexRouteImport } from './front/routes/dev/hex'
import { Route as DevSessionRouteImport } from './front/routes/dev/session'
import { Route as DevSystemRouteImport } from './front/routes/dev/system'
import { Route as DevUiRouteImport } from './front/routes/dev/ui'
import { Route as SettingsKeysRouteImport } from './front/routes/settings/keys'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRouteRoute = DevRouteRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const accessSignInRoute = accessSignInRouteImport.update({
  id: '/(access)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const accessSignUpRoute = accessSignUpRouteImport.update({
  id: '/(access)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const DevErrorsRoute = DevErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevHexRoute = DevHexRouteImport.update({
  id: '/hex',
  path: '/hex',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevSessionRoute = DevSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevSystemRoute = DevSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => DevRouteRoute,
} as any)
const SettingsKeysRoute = SettingsKeysRouteImport.update({
  id: '/settings/keys',
  path: '/settings/keys',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev': typeof DevRouteRouteWithChildren
  '/help': typeof HelpRoute
  '/mcp': typeof McpRoute
  '/sign-in': typeof accessSignInRoute
  '/sign-up': typeof accessSignUpRoute
  '/dev/errors': typeof DevErrorsRoute
  '/dev/hex': typeof DevHexRoute
  '/dev/session': typeof DevSessionRoute
  '/dev/system': typeof DevSystemRoute
  '/dev/ui': typeof DevUiRoute
  '/settings/keys': typeof SettingsKeysRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev': typeof DevRouteRouteWithChildren
  '/help': typeof HelpRoute
  '/mcp': typeof McpRoute
  '/sign-in': typeof accessSignInRoute
  '/sign-up': typeof accessSignUpRoute
  '/dev/errors': typeof DevErrorsRoute
  '/dev/hex': typeof DevHexRoute
  '/dev/session': typeof DevSessionRoute
  '/dev/system': typeof DevSystemRoute
  '/dev/ui': typeof DevUiRoute
  '/settings/keys': typeof SettingsKeysRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev': typeof DevRouteRouteWithChildren
  '/help': typeof HelpRoute
  '/mcp': typeof McpRoute
  '/(access)/sign-in': typeof accessSignInRoute
  '/(access)/sign-up': typeof accessSignUpRoute
  '/dev/errors': typeof DevErrorsRoute
  '/dev/hex': typeof DevHexRoute
  '/dev/session': typeof DevSessionRoute
  '/dev/system': typeof DevSystemRoute
  '/dev/ui': typeof DevUiRoute
  '/settings/keys': typeof SettingsKeysRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev'
    | '/help'
    | '/mcp'
    | '/sign-in'
    | '/sign-up'
    | '/dev/errors'
    | '/dev/hex'
    | '/dev/session'
    | '/dev/system'
    | '/dev/ui'
    | '/settings/keys'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev'
    | '/help'
    | '/mcp'
    | '/sign-in'
    | '/sign-up'
    | '/dev/errors'
    | '/dev/hex'
    | '/dev/session'
    | '/dev/system'
    | '/dev/ui'
    | '/settings/keys'
  id:
    | '__root__'
    | '/'
    | '/dev'
    | '/help'
    | '/mcp'
    | '/(access)/sign-in'
    | '/(access)/sign-up'
    | '/dev/errors'
    | '/dev/hex'
    | '/dev/session'
    | '/dev/system'
    | '/dev/ui'
    | '/settings/keys'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevRouteRoute: typeof DevRouteRouteWithChildren
  HelpRoute: typeof HelpRoute
  McpRoute: typeof McpRoute
  accessSignInRoute: typeof accessSignInRoute
  accessSignUpRoute: typeof accessSignUpRoute
  SettingsKeysRoute: typeof SettingsKeysRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(access)/sign-in': {
      id: '/(access)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof accessSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(access)/sign-up': {
      id: '/(access)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof accessSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/errors': {
      id: '/dev/errors'
      path: '/errors'
      fullPath: '/dev/errors'
      preLoaderRoute: typeof DevErrorsRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/hex': {
      id: '/dev/hex'
      path: '/hex'
      fullPath: '/dev/hex'
      preLoaderRoute: typeof DevHexRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/session': {
      id: '/dev/session'
      path: '/session'
      fullPath: '/dev/session'
      preLoaderRoute: typeof DevSessionRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/system': {
      id: '/dev/system'
      path: '/system'
      fullPath: '/dev/system'
      preLoaderRoute: typeof DevSystemRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/settings/keys': {
      id: '/settings/keys'
      path: '/settings/keys'
      fullPath: '/settings/keys'
      preLoaderRoute: typeof SettingsKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DevRouteRouteChildren {
  DevErrorsRoute: typeof DevErrorsRoute
  DevHexRoute: typeof DevHexRoute
  DevSessionRoute: typeof DevSessionRoute
  DevSystemRoute: typeof DevSystemRoute
  DevUiRoute: typeof DevUiRoute
}

const DevRouteRouteChildren: DevRouteRouteChildren = {
  DevErrorsRoute: DevErrorsRoute,
  DevHexRoute: DevHexRoute,
  DevSessionRoute: DevSessionRoute,
  DevSystemRoute: DevSystemRoute,
  DevUiRoute: DevUiRoute,
}

const DevRouteRouteWithChildren = DevRouteRoute._addFileChildren(
  DevRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevRouteRoute: DevRouteRouteWithChildren,
  HelpRoute: HelpRoute,
  McpRoute: McpRoute,
  accessSignInRoute: accessSignInRoute,
  accessSignUpRoute: accessSignUpRoute,
  SettingsKeysRoute: SettingsKeysRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
