/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as DevErrorsRouteImport } from './routes/dev/errors'
import { Route as DevHexRouteImport } from './routes/dev/hex'
import { Route as DevSessionRouteImport } from './routes/dev/session'
import { Route as DevSystemRouteImport } from './routes/dev/system'
import { Route as DevUiRouteImport } from './routes/dev/ui'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const DevErrorsRoute = DevErrorsRouteImport.update({
  id: '/dev/errors',
  path: '/dev/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const DevHexRoute = DevHexRouteImport.update({
  id: '/dev/hex',
  path: '/dev/hex',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSessionRoute = DevSessionRouteImport.update({
  id: '/dev/session',
  path: '/dev/session',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSystemRoute = DevSystemRouteImport.update({
  id: '/dev/system',
  path: '/dev/system',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/dev/ui',
  path: '/dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dev/errors': typeof DevErrorsRoute
  '/dev/hex': typeof DevHexRoute
  '/dev/session': typeof DevSessionRoute
  '/dev/system': typeof DevSystemRoute
  '/dev/ui': typeof DevUiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dev/errors': typeof DevErrorsRoute
  '/dev/hex': typeof DevHexRoute
  '/dev/session': typeof DevSessionRoute
  '/dev/system': typeof DevSystemRoute
  '/dev/ui': typeof DevUiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dev/errors': typeof DevErrorsRoute
  '/dev/hex': typeof DevHexRoute
  '/dev/session': typeof DevSessionRoute
  '/dev/system': typeof DevSystemRoute
  '/dev/ui': typeof DevUiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dev/errors'
    | '/dev/hex'
    | '/dev/session'
    | '/dev/system'
    | '/dev/ui'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dev/errors'
    | '/dev/hex'
    | '/dev/session'
    | '/dev/system'
    | '/dev/ui'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dev/errors'
    | '/dev/hex'
    | '/dev/session'
    | '/dev/system'
    | '/dev/ui'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  DevErrorsRoute: typeof DevErrorsRoute
  DevHexRoute: typeof DevHexRoute
  DevSessionRoute: typeof DevSessionRoute
  DevSystemRoute: typeof DevSystemRoute
  DevUiRoute: typeof DevUiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/errors': {
      id: '/dev/errors'
      path: '/dev/errors'
      fullPath: '/dev/errors'
      preLoaderRoute: typeof DevErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/hex': {
      id: '/dev/hex'
      path: '/dev/hex'
      fullPath: '/dev/hex'
      preLoaderRoute: typeof DevHexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/session': {
      id: '/dev/session'
      path: '/dev/session'
      fullPath: '/dev/session'
      preLoaderRoute: typeof DevSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/system': {
      id: '/dev/system'
      path: '/dev/system'
      fullPath: '/dev/system'
      preLoaderRoute: typeof DevSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/dev/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  DevErrorsRoute: DevErrorsRoute,
  DevHexRoute: DevHexRoute,
  DevSessionRoute: DevSessionRoute,
  DevSystemRoute: DevSystemRoute,
  DevUiRoute: DevUiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
