#!/usr/bin/env python3
"""Generate a name -> TCG Arena DOM set-id map for a deck, from sets/*/source.json.

In the TCG Arena DOM, each card image is identified by "<SET_ID>-<3-digit collector>"
(e.g. "OGN-199" for Tideturner). That id is derivable from a card's riftbound_id
("ogn-199-298" -> "OGN-199"). This reads a deck's list.json, resolves every card
name against sets/*/source.json, and writes card_ids.json next to the list. The map lets
the /games:riftbound:play contract target cards by NAME (resolved to set-id) instead of position.

Usage:
  python scripts/build_card_ids.py [deck_dir]
  (deck_dir defaults to decks/irelia_blade_dancer/tempo_disruption)
"""
import json
import os
import re
import sys
from glob import glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Cards absent from sets/*/source.json (e.g. set OGS, out of coverage) or pinned to a
# specific printing, identified by reading the card image directly in TCG Arena.
MANUAL_OVERRIDES = {
    "Flash": "OGS-011",  # set OGS, hors couverture sets/*/source.json (cf. memory/project_data_gaps)
}


def dom_id(riftbound_id):
    parts = riftbound_id.split("-")
    return "{}-{}".format(parts[0].upper(), parts[1])


def norm(name):
    # list.json uses "Name, Epithet" (comma); sets use "Name - Epithet" (dash).
    # Casing also differs (e.g. "Ride the Wind" vs "Ride The Wind"). Normalise both.
    return name.replace(", ", " - ").strip().lower()


def art_hash(card):
    # Some cards render full-art in TCG Arena as ".../game_data_live/<hash>-WxH.png"
    # instead of the "<SET-ID>/thumb" path. The hash lives in the card's image_url.
    url = (card.get("media") or {}).get("image_url") or ""
    head = url.split("/")[-1].split("?")[0].split("-")[0]
    return head if re.fullmatch(r"[0-9a-f]{20,}", head) else None


def load_index():
    index = {}        # normalised name -> set of dom_ids
    id_to_hash = {}   # dom_id -> art hash
    for path in glob(os.path.join(ROOT, "sets", "*", "source.json")):
        with open(path, encoding="utf-8") as fh:
            for card in json.load(fh):
                rid = card.get("riftbound_id")
                if not rid:
                    continue
                did = dom_id(rid)
                index.setdefault(norm(card["name"]), set()).add(did)
                h = art_hash(card)
                if h:
                    id_to_hash[did] = h
    return index, id_to_hash


def deck_names(deck_dir):
    with open(os.path.join(deck_dir, "list.json"), encoding="utf-8") as fh:
        deck = json.load(fh)
    names = []
    if deck.get("legend"):
        names.append(deck["legend"])
    if deck.get("chosen_champion"):
        names.append(deck["chosen_champion"])
    for card in deck.get("main_deck", []):
        names.append(card["name"])
    for card in deck.get("sideboard", []):
        names.append(card["name"])
    names.extend(deck.get("battlefields", []))
    for colour in deck.get("runes", {}):
        names.append("{} Rune".format(colour))
    seen, ordered = set(), []
    for name in names:
        if name not in seen:
            seen.add(name)
            ordered.append(name)
    return ordered


def main():
    arg = sys.argv[1] if len(sys.argv) > 1 else "decks/irelia_blade_dancer/tempo_disruption"
    deck_dir = arg if os.path.isabs(arg) else os.path.join(ROOT, arg)
    index, id_to_hash = load_index()

    ids, hash_ids, unresolved, ambiguous = {}, {}, [], {}
    for name in deck_names(deck_dir):
        if name in MANUAL_OVERRIDES:
            ids[name] = MANUAL_OVERRIDES[name]
            continue
        matches = sorted(index.get(norm(name), ()))
        if not matches:
            unresolved.append(name)
            continue
        chosen = matches[0]
        ids[name] = chosen
        if len(matches) > 1:
            ambiguous[name] = matches
        full_art = id_to_hash.get(chosen)
        if full_art:
            hash_ids[full_art] = chosen

    out = {
        "_about": "name -> TCG Arena DOM set-id; hash_ids maps full-art image hashes -> set-id. Generated by scripts/build_card_ids.py.",
        "ids": ids,
        "hash_ids": hash_ids,
    }
    if unresolved:
        out["_unresolved"] = unresolved
    if ambiguous:
        out["_ambiguous"] = ambiguous

    dst = os.path.join(deck_dir, "card_ids.json")
    with open(dst, "w", encoding="utf-8") as fh:
        json.dump(out, fh, ensure_ascii=False, indent=2)
        fh.write("\n")

    print("Wrote {} ({} resolved, {} unresolved, {} ambiguous)".format(
        dst, len(ids), len(unresolved), len(ambiguous)))
    if unresolved:
        print("  unresolved:", unresolved)
    if ambiguous:
        print("  ambiguous:", ambiguous)


if __name__ == "__main__":
    main()
